Algoritmo "Primeiro"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/08/2022
Var
// Seção de Declarações das variáveis 
   msg: caractere
   num: inteiro
   nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreva("digite o seu nome")
  leia(nome)
  escreva("muito prazer ", nome)
Fimalgoritmo